version: '3'
services:
  server:
    build:
      context: ./server
    environment:
        - NODE_ENV=development
    ports:
     - "3001:81"
    volumes:
     - ./server:/code
     - /code/node_modules
    tty: true
    restart: on-failure
    command: sh -c "npm run server"

  app:
    build:
      context: ./client
    environment:
        - NODE_ENV=development
    ports:
     - "3000:80"
    volumes:
     - ./server:/code
     - /code/node_modules
    tty: true
    restart: on-failure
    command: sh -c "npm run client"
  