version: '3'
networks:
  sound_network:
    driver: bridge
services:

  client:
    env_file: .env
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./client:/code
      - /code/node_modules
    networks:
      - sound_network
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    # expose:
    #   - "${CLIENT_PORT}"
    command: sh -c "npm run dev"

  server:
    env_file: .env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/code
      - /code/node_modules
    networks:
      sound_network:
        aliases:
          - ${HOST_ALIAS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # expose:
    #   - "${SERVER_PORT}"
    environment:
      WAIT_HOSTS: mongodb:${MONGO_PORT}
    command: sh -c "export GOOGLE_APPLICATION_CREDENTIALS=google-storage-auth.json; npm run dev"
    # depends_on:
    #   - mongodb
    # command: sh -c "/wait && npm run dev"
  
  # mongodb:
  #   hostname: mongodb
  #   env_file: .env
  #   image: mongo
  #   restart: always
  #   networks:
  #     - sound_network
  #   logging:
  #     driver: none
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}

  generate-local:
    env_file: .env
    build:
      context: ./models/n-synth
      args: 
        TENSORFLOW_IMAGE: tensorflow/tensorflow:1.13.1-py3
        DATASET_TYPE: real
        COMPUTE_TYPE: cpu
        COMPUTE_ENVIRONMENT: local
    volumes:
      - ./models/n-synth/artifacts:/code/artifacts
    networks:
      - sound_network
    ports:
     - "${GENERATE_PORT}:${GENERATE_PORT}"
    command: sh -c "python generate.py"
  
  generate-paperspace:
    env_file: .env
    build:
      context: ./models/n-synth
      args: 
        TENSORFLOW_IMAGE: tensorflow/tensorflow:1.13.1-gpu-py3
        DATASET_TYPE: real
        COMPUTE_TYPE: gpu
        COMPUTE_ENVIRONMENT: paperspace
    volumes:
      - ./models/n-synth/artifacts:/code/artifacts
    networks:
      - sound_network
    ports:
     - "${GENERATE_PORT}:${GENERATE_PORT}"
    command: sh -c "python generate.py"
  
  generate-test:
    env_file: .env
    build:
      context: ./models/n-synth
      args: 
        TENSORFLOW_IMAGE: tensorflow/tensorflow:1.13.1-gpu-py3
        DATASET_TYPE: test
        COMPUTE_TYPE: gpu
        COMPUTE_ENVIRONMENT: paperspace
    volumes:
      - ./models/n-synth/artifacts:/code/artifacts
    networks:
      - sound_network
    ports:
     - "${GENERATE_PORT}:${GENERATE_PORT}"
    command: sh -c "python generate.py"
