version: '3'
networks:
  sound_network:
    driver: bridge
services:

  client:
    hostname: client
    env_file: .env
    build:
      context: ./client
    restart: always
    volumes:
      - ./client:/code
      - /code/node_modules
    networks:
      - sound_network
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    expose:
      - "${CLIENT_PORT}"
    command: sh -c "npm run start"