version: '3'
services:
  gan-synth-cpu:
    build:
      context: ./apps/gan-synth
      args: 
        TENSORFLOW_IMAGE: tensorflow/tensorflow:1.13.1-py3
        COMPUTE_TYPE: cpu
        STORAGE_DIR: './storage'
        ARTIFACTS_DIR: './artifacts'
    ports:
     - "80:4000"
    tty: true
    restart: on-failure
    command: sh -c "python mock-job.py"
  