version: '3'
services:
  n-synth:
    build:
      context: ./models/n-synth
      args: 
        TENSORFLOW_IMAGE: tensorflow/tensorflow:1.13.1-py3
        COMPUTE_TYPE: cpu
        COMPUTE_ENVIRONMENT: local
    volumes:
        - ./models/n-synth/artifacts:/code/jobs/encode-interpolate/artifacts
        - ./models/n-synth/storage:/code/jobs/encode-interpolate/storage
        - ./models/n-synth/artifacts:/code/jobs/decode/artifacts
        - ./models/n-synth/storage:/code/jobs/decode/storage
    ports:
     - "80:4000"
    tty: true
    restart: on-failure
    command: sh -c "python generate.py"
  