version: '3'
services:
  n-synth:
    build:
      context: ./models/n-synth
      args: 
        TENSORFLOW_IMAGE: tensorflow/tensorflow:1.13.1-py3
        COMPUTE_TYPE: cpu
        STORAGE_DIR: './storage'
        ARTIFACTS_DIR: './artifacts'
        BATCH_SIZE_SAVE_EMBEDDINGS: 1
    volumes:
        - ./models/n-synth/artifacts:/code/job/artifacts
        - ./models/n-synth/storage:/code/job/storage
        - ./models/n-synth/job/data:/code/job/data
    ports:
     - "80:4000"
    tty: true
    restart: on-failure
    command: sh -c "python mock-job.py"
  